### PR TITLE
Fix location entry delete issue fixes #1

### LINKED ISSUE #1: Delete the location data base entries if the last entry is 15 minutes old
Now the app deletes the location database entries if the first entry is 15 minutes older. But it has to be changed to the last entered location has to be 15 minutes older to wipe out the whole database entries.

### PR DESCRIPTION
**Pull request by sdglhm**
This issue can be resolve via using millis time entry and firebase endAt

 fixes #1

### CODE REVIEW

**Comment by Batzee** [comment]
What you are trying to is get the data that are exactly 15 minutes old.
What I want to do is remove all the entries that are greater that 15 minutes old. 
Can you able to do that modification?
Then I can merge your pull request

Thank You
:)

**Comment by sdglhm** [comment]
Awesome. Will do.

**Comment by Batzee** [comment]
Whats the Status?

**Comment by sdglhm** [comment]
Hey, Sorry about the delay.

Having some issues setting up application to run.

**Comment by Batzee** [comment]
Were you able to fix it and run?

**Review by Batzee — APPROVED** [review]

**Pull request merged**
